/* 
 * Mpesa  Service
 *
 * This is an internal Mpesa Service that communicates via REST to the Safaricom Daraja API
 *
 * OpenAPI spec version: 1.0
 * Contact: ondengew@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Use this API to transact between an M-Pesa short code to a phone number registered on M-Pesa.
type B2CPayload struct {

	// The amount been transacted
	Amount float64 `json:"Amount"`

	// Unique command for each transaction type
	CommandID string `json:"CommandID"`

	// The name of the initiator initiating the request
	InitiatorName string `json:"InitiatorName"`

	// Optional Parameter
	Occasion string `json:"Occasion"`

	// Organization /MSISDN sending the transaction
	PartyA float64 `json:"PartyA"`

	// MSISDN sending the transaction
	PartyB float64 `json:"PartyB"`

	// The path that stores information of time out transaction
	QueueTimeOutURL string `json:"QueueTimeOutURL"`

	// Comments that are sent along with the transaction. 
	Remarks string `json:"Remarks"`

	// The path that stores information of transactions
	ResultURL string `json:"ResultURL"`

	// Encrypted Credential of user getting transaction amount
	SecurityCredential string `json:"SecurityCredential"`
}
