/* 
 * Mpesa  Service
 *
 * This is an internal Mpesa Service that communicates via REST to the Safaricom Daraja API
 *
 * OpenAPI spec version: 1.0
 * Contact: ondengew@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"net/url"
	"strings"
)

type B2cApi struct {
	Configuration *Configuration
}

func NewB2cApi() *B2cApi {
	configuration := NewConfiguration()
	return &B2cApi{
		Configuration: configuration,
	}
}

func NewB2cApiWithBasePath(basePath string) *B2cApi {
	configuration := NewConfiguration()
	configuration.BasePath = basePath

	return &B2cApi{
		Configuration: configuration,
	}
}

/**
 * create b2c
 * creates a b2c payment request
 *
 * @param authorization 
 * @param xAccount 
 * @param payload Use this API to transact between an M-Pesa short code to a phone number registered on M-Pesa.
 * @return void
 */
func (a B2cApi) B2cCreate(authorization string, xAccount int32, payload B2CPayload1) (*APIResponse, error) {

	var localVarHttpMethod = strings.ToUpper("Post")
	// create path and map variables
	localVarPath := a.Configuration.BasePath + "/b2c/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := make(map[string]string)
	var localVarPostBody interface{}
	var localVarFileName string
	var localVarFileBytes []byte
	// add default headers if any
	for key := range a.Configuration.DefaultHeader {
		localVarHeaderParams[key] = a.Configuration.DefaultHeader[key]
	}

	// to determine the Content-Type header
	localVarHttpContentTypes := []string{ "application/json",  }

	// set Content-Type header
	localVarHttpContentType := a.Configuration.APIClient.SelectHeaderContentType(localVarHttpContentTypes)
	if localVarHttpContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHttpContentType
	}
	// to determine the Accept header
	localVarHttpHeaderAccepts := []string{
		"application/json",
		}

	// set Accept header
	localVarHttpHeaderAccept := a.Configuration.APIClient.SelectHeaderAccept(localVarHttpHeaderAccepts)
	if localVarHttpHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHttpHeaderAccept
	}
	// header params "Authorization"
	localVarHeaderParams["Authorization"] = a.Configuration.APIClient.ParameterToString(authorization, "")
	// header params "X-Account"
	localVarHeaderParams["X-Account"] = a.Configuration.APIClient.ParameterToString(xAccount, "")
	// body params
	localVarPostBody = &payload
	localVarHttpResponse, err := a.Configuration.APIClient.CallAPI(localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)

	var localVarURL, _ = url.Parse(localVarPath)
	localVarURL.RawQuery = localVarQueryParams.Encode()
	var localVarAPIResponse = &APIResponse{Operation: "B2cCreate", Method: localVarHttpMethod, RequestURL: localVarURL.String()}
	if localVarHttpResponse != nil {
		localVarAPIResponse.Response = localVarHttpResponse.RawResponse
		localVarAPIResponse.Payload = localVarHttpResponse.Body()
	}

	if err != nil {
		return localVarAPIResponse, err
	}
	return localVarAPIResponse, err
}

