/* 
 * Payments API Gateway
 *
 * This is an internal payments API gateway for Chamaconekt Kenya 
 *
 * OpenAPI spec version: 0.1
 * Contact: ondengew@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// A tenant account (default view)
type MediatypeIdentifierApplicationvndAccountjsonViewdefault struct {

	// Date of creation
	CreatedAt time.Time `json:"created_at"`

	// Email of account owner
	CreatedBy string `json:"created_by"`

	// API href of account
	Href string `json:"href"`

	// ID of account
	Id int64 `json:"id"`

	// Name of account
	Name string `json:"name"`
}
