/* 
 * Payments API Gateway
 *
 * This is an internal payments API gateway for Chamaconekt Kenya 
 *
 * OpenAPI spec version: 0.1
 * Contact: ondengew@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type UpdateAccountPayload1 struct {

	// Name of account
	Name string `json:"name"`
}
